# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
# IMPORTANT: You must stop your jekyll build --watch command, and re-run after any changes are made here,
# in order for changes to this file to go into effect
#
title: Digital Security Exchange
email: ops@digitalsecurityexchange.org
description: >- # this means to ignore newlines until "baseurl:"
  Digital Security Exchange.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Server Config options
livereload: false     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port

topnav:
- { title: 'About', href: '/about/' }
- { title: 'Support the DSX', href: '/support/' }
- { title: 'Partner Log In', href: 'https://staging.civicdr.org' }

footernav:
- { title: 'DSX at a Glance', href: '/at-a-glance' }
- { title: 'Become a Provider', href: '/become-a-provider/' }
- { title: 'Request Assistance', href: '/request-assistance/' }

- { title: 'About', href: '/about' }
- { title: 'News', href: '/updates' }

mainnav:
- { title: 'DSX at a Glance', href: '/at-a-glance' }
- { title: 'Request Assistance', href: '/request-assistance/' }
- { title: 'Become a Provider', href: '/become-a-provider/' }
- { title: 'News', href: '/updates' }

finenav:
- { title: 'Privacy', href: '/privacy' }
- { title: 'Security', href: '/security' }
- { title: 'Terms of Use', href: '/terms' }

getStartedCardData:
- { number: '1', title: 'Request assistance', content: 'Get assistance for you or your organization', color: '$cyan', link: '/request-assistance' }
- { number: '2', title: 'Become a provider', content: 'Request to become a digital security provider with the DSX', color: '$peach', link: '/become-a-provider' }

howItWorksCardData:
- { number: '1', title: 'Request digital security assistance', href: '/request-assistance', content: 'Civil society organizations come to the Digital Security Exchange seeking help with digital security assessments and training.', graphic: 'svg-howItWorks1.html' }
- { number: '2', title: 'Request to become a provider', href: '/become-a-provider', content: 'Digital security experts interested in assisting organizations request to become providers with the DSX.', graphic: 'svg-howItWorks2.html' }
- { number: '3', title: 'Learn more about how the DSX Partnership Program', href: '/partners', content: 'Organizations in need connect with digital security experts who can provide support.', graphic: 'svg-howItWorks3.html' }

tagLine:
  line1: 'Keeping U.S. civil society'
  line2: 'safe from digital attack'


sass:
  sass_dir: css
  style: compressed

keep_files: ['forms']

exclude:
- README.md
- LICENSE.md
- submissions
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
